### ISSUE TITLE
Change branch

### ISSUE THREAD

**Issue by jareciog** [isee4xai/ExplanationExperienceEditor#2]
Hi Bruno.
We need to deploy branch Editor, instead Master.

Thank you

**Comment by bfleisch** [comment]
as discussed:

* I have created a development branch called 'dev' that has CI/CD integrate
* I'll merge all changes from the 'Editor' branch into the 'dev' branch

**Comment by bfleisch** [comment]
NB: the old 'Editor' branch has been deleted to prevent further issue
